# Generated by Django 5.1.3 on 2024-11-06 00:50

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_file',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
