# Generated by Django 5.1.3 on 2024-11-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_image_file_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
