# Generated by Django 5.1.3 on 2024-11-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cartitem_user_alter_log_user_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
