# Generated by Django 5.1.3 on 2024-11-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_user_cartitem_user_id_rename_user_log_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
